class TestData:
    BASE_URL = "https://the-internet.herokuapp.com"
    USER_NAME = "tomsmith"
    User_PASSWORD = "SuperSecretPassword!"
    LOGIN_PAGE_TITLE = "The Internet"
    LOGIN_PAGE_HEADER = "Login Page"
    LOGIN_MESSAGE = "You logged into a secure area!"
    LOGOUT_MESSAGE = "You logged out of the secure area!"
    CHECKBOX_HEADER = "Checkboxes"
    BASIC_AUTH_MESSAGE = "Congratulations! You must have the proper credentials"
    USERNAME = "admin"
    PASSWORD = "admin"
    ALERT = "You selected a context menu"
